### ISSUE TITLE
Button "click me" is not working

### ISSUE THREAD

**Issue by tech-anand247** [getfullstack/FirstRepository#5]
Steps to reproduce
1. Go to home
2. Click on "click me" button
![531954_7380_2](https://cloud.githubusercontent.com/assets/23119676/19806176/b368c576-9d36-11e6-861d-2af594959592.jpg)

**Comment by getfullstack** [comment]
I will look into it. Meanwhile, you work with command line.

**Comment by getfullstack** [comment]
I am done with it. Hope it works now.
